# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a72463e5-f16d-4c17-b12d-281930ee1bc8";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a72463e5-f16d-4c17-b12d-281930ee1bc8";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a72463e5-f16d-4c17-b12d-281930ee1bc8";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a72463e5-f16d-4c17-b12d-281930ee1bc8";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@log" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
