wallpaper {
    monitor = eDP-1
    path = ~/.config/wallpaper/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = LVDS-1
    path = ~/.config/wallpaper/wallpaper.jpg
    fit_mode = cover
}

# preload = ~/.config/wallpaper/wallpaper.jpg
# wallpaper = , ~/.config/wallpaper/wallpaper.jpg