wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper/wallpaper.jpg
    fit_mode = cover
}

# preload = ~/.config/hypr/wallpaper/wallpaper.jpg
# wallpaper = , ~/.config/hypr/wallpaper/wallpaper.jpg